<Project>
  <PropertyGroup>
    <InstallerArtifactsRoot Condition="'$(InstallerArtifactsRoot)' == ''">$(MSBuildThisFileDirectory)outputs\</InstallerArtifactsRoot>
    <BaseIntermediateOutputPath>$(InstallerArtifactsRoot)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(InstallerArtifactsRoot)bin\$(MSBuildProjectName)\</BaseOutputPath>
  </PropertyGroup>
</Project>
