<Project>
  <PropertyGroup>
    <Version>1.0.7</Version>
    <AssemblyVersion>1.0.7.0</AssemblyVersion>
    <FileVersion>1.0.7.0</FileVersion>
    <InstallerArtifactsRoot Condition="'$(InstallerArtifactsRoot)' == ''">$(MSBuildThisFileDirectory)outputs\</InstallerArtifactsRoot>
    <BaseIntermediateOutputPath>$(InstallerArtifactsRoot)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(InstallerArtifactsRoot)bin\$(MSBuildProjectName)\</BaseOutputPath>
  </PropertyGroup>
</Project>
